Switch
Kartynnikk/js pull request #4
Opened 2022-08-15 20:17 UTC by Kartynnikk

2022-08-16 19:20 UTC, kathrynowy requested changes

2022-08-16 19:20 UTC, kathrynowy commented on switch.html
> +        if (browser == "Edge") {
strict comparison

2022-08-29 19:51 UTC, kathrynowy requested changes

2022-08-29 19:51 UTC, kathrynowy commented on switch.html
> +</html>
eof

2022-08-30 16:30 UTC, Kartynnikk commented on switch.html
> +        if (browser == "Edge") {
fixed

2022-08-30 16:30 UTC, Kartynnikk commented on switch.html
> +</html>
fixed

2022-09-03 06:05 UTC, kathrynowy approved these changes

2022-09-03 18:12 UTC, merged