Addex
Kartynnikk/js pull request #5
Opened 2022-08-15 21:24 UTC by Kartynnikk

2022-08-16 19:33 UTC, kathrynowy requested changes

2022-08-16 19:33 UTC, kathrynowy commented on addex.html
> +        if (str[0] == "a") {
strict comparison

2022-08-16 19:33 UTC, kathrynowy commented on addex.html
> +        if (num[0] == "1" || num[0] == "2" || num[0] == "1") {
two same conditions

2022-08-29 19:55 UTC, kathrynowy requested changes

2022-08-29 19:55 UTC, kathrynowy commented on addex.html
> +        if (num[0] == "1" || num[0] == "2") {
strict comparison!

2022-08-30 16:24 UTC, Kartynnikk commented on addex.html
> +        if (str[0] == "a") {
fixed

2022-08-30 16:24 UTC, Kartynnikk commented on addex.html
> +        if (num[0] == "1" || num[0] == "2" || num[0] == "1") {
fixed

2022-08-30 16:24 UTC, Kartynnikk commented on addex.html
> +        if (num[0] == "1" || num[0] == "2") {
fixed

2022-09-03 06:06 UTC, kathrynowy approved these changes

2022-09-03 18:13 UTC, merged